### ISSUE TITLE
Unexpected AssertionErrors on model manipulation

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#14]

**Comment by anthonyanjorin** [comment]
Hi Greg,

I've now had some time to inspect this test (the only test failing on your ``democles-debug``) branch.  

The test still produces an AssertionError from Democles.  I've found out that the EObject is not really deleted correctly (just removed from it's container), but nonetheless, you might want to investigate and make things more robust or produce a useful error message explaining what is wrong (such a "deletion" can in general be performed, or not?).

Cheers and thanks,
Tony

**Comment by gervarro** [comment]
Hi Tony,

Producing useful error messages is definitely on my todo list for the near future, however, I wanted to raise a topic on the fruitful cooperation of the incremental pattern matcher and the TGG engine.

EMF notification adapters rely on the correctness of the containment hierarchy, and if an `EObject` is manipulated outside the containment hierarchy then incremental engines can only produce scrap as a result. The real problematic part is that if the notification processing module is permissive, then it is extremely easy to produce inconsistent models (from an incremental engine perspective), for which the correctness of the match set cannot be ensured. The Democles engine converts models and EMF notifications into a common event sequence, which is later used by the pattern matcher itself. In order to avoid the above-mentioned mess, Democles uses extremely strict rules on what kind of model manipulations are allowed.

In the `testDeleteDaughter` case, a `FamilyMember` becomes a hanging node when the corresponding `daughters` containment reference is removed. This is not yet a problem, as Democles marks the complete subtree along the containment hierarchy as hanging. However, modifications, in which hanging objects are involved, are forbidden, otherwise the consistency of the internal state (i.e., the match set) of the PM cannot be ensured. Ibex currently removes objects from the correspondence model after the modifications in the source and target model, which is implicitly categorized as a manipulation on a hanging object as an object in the correspondence model typically maintains source and target links to the domain models. These links are not explicitly set to null in the current setup (i.e., incremental engine should handle this but no notification is issued by EMF), only the correspondence object is removed. Democles implicitly removes these source and target edges (to maintain consistency in the match set), although they still exist in the model (which currently results in a bug as Democles tries to avoid replicating the complete model).

I am planning to make the notification processing module more restrictive, which would require the following modification order in the Ibex engine:
1. Set source and target links leaving the correspondence object explicitly to null.
2. Remove correspondence object from the containment hierarchy.
3. Remove objects from the source or target model.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Hi Greg,

Ok, that's interesting.

We are fully in control of the correspondence model, so (1) and (2) shouldn't be a problem.

The problem with (3), however, is that TGG rules are free to create (and thus dually delete when being revoked) model elements in any order.  This means that the models can be disjunct at any point in time.

Should we introduce a kind of "default container" to contain all dangling nodes until they again have a container later in the process?  Would that also solve the problem?

@erhanleblebici Do you any problems here?

Cheers,
Tony

**Comment by gervarro** [comment]
Hi Tony,

could you please wait with changing anything in the Ibex engine? This issue actually helps me clarifying what should be allowed / forbidden in the pattern matcher. I do not want to restrict anything without a good reason. In the first round, I wanted to call your attention in the above long comment to the special requirements of an incremental engine.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
No problem  - your branch is stable (and can remain as it is as long as you want it to).

**Comment by anthonyanjorin** [comment]
Hi Greg,

I've been trying to understand how this works and I still don't get it:

If I use ``EcoreUtil.delete(lisa)`` to delete a person, what happens is:

1.  All cross-references of lisa are set to null (including all connections to the correspondence elements) 
2. Lisa is finally removed from the person register

Why should this still trigger an exception?  Lisa is hanging but I'm quite sure that no changes are performed later that affect the object in anyway.

Any ideas?  We are trying to compile now a substantial set of tests and this problem is blocking us in many cases :(

Thanks,
Tony

**Comment by anthonyanjorin** [comment]
I've now double-checked as best as I can that the deleted object is no longer referenced by anything before it is detached from its container.

The invalidated match is also registered as expected, but then an assertion fails *before* we are able to do anything at all (nothing additionally is deleted).

**Comment by anthonyanjorin** [comment]
I have now debugged another test concerning only the model generator.  In this case an AssertionException is thrown as soon as a newly created node is attached to the containment hierarchy.  The exception complains about the setting of an attribute value of the node but this must be a bug.  Attribute values that are primitive values are of course set to some default value (e.g., ints are set to 0) and there is no way to do this "after" adding the node to the containment hierarchy.

Btw:  disabling assertions shows that everything works fine, perhaps indicating that the assertion is erroneous in this case.

We'll compile your branch (hopefully tomorrow) with all tests that are failing due to assertions we cannot understand and fix.

Cheers,
Tony

**Comment by gervarro** [comment]
Hi,

could you please send me the sources of the Ibex.jar file in some form? It is difficult to follow what is going on without knowing the details on the TGG level.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Sorry, I'll fix this in a minute.  The source should of course be included in the jar.

**Comment by anthonyanjorin** [comment]
ok, please pull and check, fix should now be on your branch.

**Comment by gervarro** [comment]
Hi Tony,

thanks for the sources. There are different kinds of assertion errors. One of them, which blocked the half of the tests, has been fixed. EMF behaves a bit strange in case of attributes of primitive types. As you also recognized, EMF uses default values for attributes, which has to be reported explicitly to an incremental engine (during initialization). The more problematic part is that an attribute is considered unset in EMF (i.e., `eIsSet()` returns `false`) if it is set to the default value, which caused problems when an object was deleted, as the "deletion" of the corresponding default value was not reported.

The fix will be available on the update sites next week (together with other fixes). Please leave this issue open, as there is another kind of assertion error, which still causes test failure.

Bests,
Greg

**Comment by gervarro** [comment]
Hi Tony,

I fixed the other assertion error as well. It was a bug in an earlier bug fix (a condition was too strict). Tests might eventually still fail (i.e., not in each execution). I checked the erroneous situation, and it seems as the source link of the correspondence object, which originally points to `Lisa` is not always set to null (or at least the corresponding notification is missing). In which step should it be set to `null`? Could you please check this case? (You can download the latest version from the 2 update sites that fixes the 4 issues (2 here, #15, and #16) from this month.)

Bests,
Greg

**Comment by gervarro** [comment]
Hi Tony,

my latest analysis shows that a `FamilyMember` (i.e., `Lisa`) is still removed earlier from its container than the `source` link of the `FamilyMemberToPerson` is set to `null`, which leads to problems in case of some search plans. More precisely, the problem occurs when a rule is revoked as correspondence nodes are removed after source and target edges are deleted (see https://github.com/eMoflon/emoflon-ibex/blob/a9ac2a7cd963ac936d9badb4e753621b73ee602e/org.emoflon.ibex.tgg.core.runtime/src/org/emoflon/ibex/tgg/operational/OperationalStrategy.java#L451-L452). Would it be possible to remove correspondence nodes first, and then to manipulate domain (source and target) model elements?


Bests,
Greg

**Comment by anthonyanjorin** [comment]
Ahh that's right!  Yes, that can be definitely fixed.
