### ISSUE TITLE
Assertion error from Democles on invoking updateMatches

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-democles#5]
Hi Greg,

I have a new problem now in `testsuite2_familiestopersons::testsuite1.familiestopersons.sync.AlignmentBased.testDeleteDaughter()`

If you update your test projects and run the tests, `testDeleteDaughter` will fail due to an AssertionError thrown for some reason by Democles.

I don't expect the test to pass (yet), but I don't even get a chance to react to any broken matches (something is getting deleted).

Any ideas what is going wrong?

Cheers and thanks,
Tony

**Comment by anthonyanjorin** [comment]
@gervarro I've pushed the latest changes to master, please inform me if you cannot reproduce the error.

**Comment by gervarro** [comment]
Hi Tony,

the problem has been identified. I only need some time in quiet to find a proper solution.

Bests,
Greg

**Comment by gervarro** [comment]
Hi Tony,

Sorry. This was a somewhat larger issue that affected the deepest parts of the pattern matcher. Type checking on `EObject`s had to be handled specially in case of deletions in incremental mode. I could not test the fix on your TGG test cases, because the Democles configuration must be updated by replacing `org.gervarro.democles.runtime.GenericOperationBuilder` with the new `org.gervarro.democles.operation.emf.EMFBatchOperationBuilder`, and the configuration is now located in the Ibex.jar file that I could not change. Fix is available on the update site.

Bests,
Greg

**Comment by anthonyanjorin** [comment]
Hi Greg,

I've now replaced the old line in the set up with:

`		final EMFBatchOperationBuilder<VariableRuntime> emfBatchOperationModule = new EMFBatchOperationBuilder<VariableRuntime>(emfNativeOperationModule, DefaultEMFBatchAdornmentStrategy.INSTANCE);
`

Is that ok?

I've updated the Ibex.jar in all testsuites on your branch and pushed the changes.  There are now multiple NPE exceptions so I guess something is not yet configured correctly.

Thanks,
Tony

**Comment by anthonyanjorin** [comment]
Ok - I can't reproduce this on *master*,  I'll close the issue for now until I have time to work a bit more on the test.  Thanks!

**Comment by gervarro** [comment]
Hi Tony,

I uploaded a fix yesterday that eliminates the NPE, and solves another problematic case. However, there is still an issue with the test case that is related to the incremental PM friendliness of the TGG engine (see #14).

Bests,
Greg
