### ISSUE TITLE
GT: Democles reports invalid matches for pattern with self reference

### ISSUE THREAD

**Issue by patrickrobrecht** [eMoflon/emoflon-ibex-democles#74]
Democles reports invalid matches for the following pattern:

![democles-pattern-self-reference-no-invocation](https://user-images.githubusercontent.com/12370952/41092723-13b33634-6a39-11e8-8cb2-c1b403b66397.png)

Democles reports all platforms which have at least one `neighbors` edge - even if the target of the edge is not the platform itself.

The example can be found in the branch `gt-bug-self-reference` when running the TestsuiteGT. The generated Democles patterns can be found in the folder `debug/SheRememberedCaterpillars/democles-patterns.xmi`, the instance used for the test is  `instance/SheRememberedCaterpillars/Instance1.xmi`.

What's wrong here? The Democles behavior or the pattern we generate in eMoflon::IBeX-GT?

**Comment by gervarro** [comment]
The expected behaviour would be to list only those platforms that have a self-reference to themselves. My current impression is that a transformation is most probably erroneous (not necessarily on the IBeX side) as the pattern matcher returns results for a semantically different pattern (platform with at least one `neighbors` edge).

**Comment by patrickrobrecht** [comment]
The resulting Democles pattern contains an EMFVariable platform and a body with just one reference with two parameters, both pointing to the EMFVariable platform. That seems to be the correct pattern for me, isn't it?

**Comment by patrickrobrecht** [comment]
Update: This test case has been integrated into the master branch (ignored case `org.emoflon.ibex.gt.testsuite.SheRememberedCaterpillars.SheRememberedCaterpillarsConstraintsTest.findPlatformWithSelfNeighborship`). So instead of switching the branch, you can check it by removing the `@Ignore`.

**Comment by gervarro** [comment]
Hi Patrick,

this is a bug, or more precisely a feature that has not been implemented yet. As a temporary solution, I would suggest using the following two constraints `neighbors(p,localP)` and `equals(p,localP)` in the pattern specification instead of the single `neighbors(p,p)` constraint. This temporary solution is not necessarily good from a performance point of view, but it returns at least a correct match set.

Please leave this issue open, until I can fix the bug in the pattern matcher.

Bests,
Greg

**Comment by patrickrobrecht** [comment]
Hi Greg,

I think we won't implement a temporary workaround and wait for a bugfix in Democles instead.

Bests,
Patrick

**Comment by gervarro** [comment]
Hi,

the fix is available on the Democles update sites.

Bests,
Greg
